language: python
python:
  - "2.7"
  - "3.6"
env:
  global:
    - NODE_VERSION="8.10.0"
  matrix:
    - DJANGO=1.11 

before_install:
  - nvm install $NODE_VERSION

install:
  - pip install -U setuptools
  - pip install coveralls
  - if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then pip install -r requirements.python3.txt; else pip install -r requirements.txt;  fi
  - # test -e "requirements.$TRAVIS_BRANCH.txt" && ( pip install -r "requirements.$TRAVIS_BRANCH.txt" ) || ( pip install -r requirements.txt )
  - pip install Django==$DJANGO
  - nvm install $NODE_VERSION
  - npm install 
  - pip install -e .

script:
  - export LINO_CACHE_ROOT=$TRAVIS_BUILD_DIR/lino_cache
  - mkdir $LINO_CACHE_ROOT
  - inv cov

after_script:
  - coveralls report

