language: python
python:
  - "2.7"
  - "3.6"
env:
  matrix:
    - DJANGO=1.11 


install:
  - pip install -U setuptools
  - pip install coveralls
  - if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then pip install -r requirements.python3.txt; else pip install -r requirements.txt;  fi
  - # test -e "requirements.$TRAVIS_BRANCH.txt" && ( pip install -r "requirements.$TRAVIS_BRANCH.txt" ) || ( pip install -r requirements.txt )
  - pip install Django==$DJANGO
  - nvm install $NODE_VERSION
  - npm install 
  - pip install -e .

script:
  - export LINO_CACHE_ROOT=$TRAVIS_BUILD_DIR/lino_cache
  - mkdir $LINO_CACHE_ROOT
  - cd lino_react/projects/teamReact/
  - python manage.py prep --noinput
  - python manage.py runserver -v 0 > /dev/null 2>&1 &
  - sleep 15
  - npm run cy:run
  - kill $(jobs -p) || true
  - inv cov

after_script:
  - coveralls report

