dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

os: linux
sudo: required

install:
  - sudo apt-get update -y
  - sudo apt-get upgrade -y
  - sudo apt-get install -y swig
  - sudo apt-get install -y graphviz
  - sudo apt-get install redis-server ; redis-server &
  - sudo apt-get install -y tidy libreoffice python3-uno
  - pip install -U setuptools
  - pip install coveralls
  - pip install -r requirements.python3.txt
  - # test -e "requirements.$TRAVIS_BRANCH.txt" && ( pip install -r "requirements.$TRAVIS_BRANCH.txt" ) || ( pip install -r requirements.txt )
  - npm install
  - pip install -e .

script:
  - export LINO_CACHE_ROOT=$TRAVIS_BUILD_DIR/lino_cache
  - mkdir $LINO_CACHE_ROOT
  - cd lino_react/projects/teamReact/
  - python manage.py prep --noinput
  - python manage.py runserver -v 0 > /dev/null 2>&1 &
  - cd -
  - sleep 15
  - npm run cy:run -- --spec cypress/integration/teamReact/* --config video=false
  - kill $(jobs -p) || true
  - inv cov

after_script:
  - coveralls report
